FORMAT: 1A
HOST: http://speedsell.apiblueprint.org/

# SpeedSell

SpeedSell is a resource that shows main features of it's parts (Lots, 
Bids, Feedbacks and Payments.

## Lots [/lots]
###Show all available lots [GET]

+ Response 200 (application/json)

        [
            {
                "Id": "4562803",
                "name": "Apple Iphone 6s 128Gb Plus",
                "info": "Sell my iphone cause i need money for smth",
                "category": {
                                "name": "Smartphones",
                                "parentCategory": "Electronics"
                            },
                "state": "CREATED",
                "buyPrice": "120",
                "commission": "10", 
                "startPrice": "100",
                "startDate": "2016-07-12T09:00:00",
                "duration": "3600",
                "redemtion": "150"
            }
        ]


### Create new lot [POST]
Creating new lot.

+ Request (application/json)

        {
                "name": "Lenovo ThinkPad E430c",
                "info": "New laptop for home usage",
                "category": {
                                "name": "Laptops",
                                "parentCategory": "Electronics"
                            },
                "state": "CREATED",
                "buyPrice": "1200",
                "commission": "30", 
                "startPrice": "1000",
                "startDate": "2016-07-12T09:00:00",
                "duration": "3600",
                "redemtion": "1500"
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /lots/4562804
            
    + Body
    
            {
            "Id": "4562804",
            "name": "Lenovo ThinkPad E430c",
            "info": "New laptop for home usage",
            "category": {
            "name": "Laptops",
            "parentCategory": "Electronics"
            },
            "state": "CREATED",
            "buyPrice": "1200",
            "commission": "30", 
            "startPrice": "1000",
            "startDate": "2016-07-12T09:00:00",
            "duration": "3600",
            "redemtion": "1500"
            }
            
###Delete lot [DELETE]
Deleting lot by id.

+ Request (application/json)

        {
            "Id": "4562804",
        }
        

+ Response 200 (application/json)

        {
            "OK" : "Lot successfully deleted"
        }
        
+ Response 401 (text/plain)

        Please authorize to see this!
        
+ Response 404 (text/plain)

        No such lot.
        

#GET /lots/{id}
Show one particular lot 

+ Response 200 (application/json)

            {
                "Id": "4562803",
                "name": "Apple Iphone 6s 128Gb Plus",
                "info": "Sell my iphone cause i need money for smth",
                "category": {
                                "name": "Smartphones",
                                "parentCategory": "Electronics"
                            },
                "state": "CREATED",
                "buyPrice": "120",
                "commission": "10", 
                "startPrice": "100",
                "startDate": "2016-07-12T09:00:00",
                "duration": "3600",
                "redemtion": "150"
            }

#GET /users/{id}/lots
Show all lots created by some user

+ Parameters
    + id: `1` (number, required) - Id of a user.
+ Response 200 (application/json)

        [
            {
               {
                "Id": "4562803",
                "name": "Apple Iphone 6s 128Gb Plus",
                "info": "Sell my iphone cause i need money for smth",
                "category": {
                                "name": "Smartphones",
                                "parentCategory": "Electronics"
                            },
                "state": "CREATED",
                "buyPrice": "120",
                "commission": "10", 
                "startPrice": "100",
                "startDate": "2016-07-12T09:00:00",
                "duration": "3600",
                "redemtion": "150"
            },
            
            {
                "Id": "4562804",
                "name": "Lenovo ThinkPad E430c",
                "info": "New laptop for home usage",
                "category": {
                                "name": "Laptops",
                                "parentCategory": "Electronics"
                            },
                "state": "CREATED",
                "buyPrice": "1200",
                "commission": "30", 
                "startPrice": "1000",
                "startDate": "2016-07-12T09:00:00",
                "duration": "3600",
                "redemtion": "1500"

        }
        ]
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No lots yet.
        

#GET /categories/{id}/lots
Show all lots in some category

+ Parameters
    + id: `1` (number, required) - Id of a category.
+ Response 200 (application/json)

        [
            {
               {
                "Id": "4562803",
                "name": "Apple Iphone 6s 128Gb Plus",
                "info": "Sell my iphone cause i need money for smth",
                "category": {
                                "name": "Smartphones",
                                "parentCategory": "Electronics"
                            },
                "state": "CREATED",
                "buyPrice": "120",
                "commission": "10", 
                "startPrice": "100",
                "startDate": "2016-07-12T09:00:00",
                "duration": "3600",
                "redemtion": "150"
            },
            
            {
                "Id": "4562804",
                "name": "Lenovo ThinkPad E430c",
                "info": "New laptop for home usage",
                "category": {
                                "name": "Laptops",
                                "parentCategory": "Electronics"
                            },
                "state": "CREATED",
                "buyPrice": "1200",
                "commission": "30", 
                "startPrice": "1000",
                "startDate": "2016-07-12T09:00:00",
                "duration": "3600",
                "redemtion": "1500"

        }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No lots yet.
        



## Bids [/bids]

###Make bid[POST]
User can choose the lot and make his pown bid

+ Request (application/json)

        {
            "amount": "240",
            "ownerId": "7531866",
            "lotId" : "457861"
        }

+ Response 201 (application/json)

    + Headers

            Location: /bids/32

    + Body

            {
                "Id":"2345124",
                "bidDate": "2016-10-10T10:00:00",
                "amount": "240",
                "ownerId": "7531866",
                "lotId" : "457861"
            }


#GET /users/{id}/bids
You can get list of all bids made by some user.
+ Request (application/json)

        {
            "ownerId": "7531864"
        }

+ Response 200 (application/json)

        [
        {
            "Id":"2345123",
            "bidDate": "2016-10-10T09:00:00",
            "amount": "234",
            "ownerId": "7531864",
            "lotId" : "457861"
            
        },
        {
            "Id":"2345188",
            "bidDate": "2016-11-10T09:00:00",
            "amount": "2234",
            "ownerId": "7531864",
            "lotId" : "4578"
            
        }
        ]
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
        
+ Response 401 (application/json)

        {
            "error" : "You are unauthorized to make this request." 
        }
        
#GET /lots/{id}/bids
Show the history of bids, who and when made bids.
+ Request (application/json)

        {
            "lotId": "457861"
        }

+ Response 200 (application/json)

        [
        {
            "Id":"2345123",
            "bidDate": "2016-10-10T09:00:00",
            "amount": "234",
            "ownerId": "7531864",
            "lotId" : "457861"
            
        },
        {
            "Id":"2345124",
            "bidDate": "2016-10-10T10:00:00",
            "amount": "240",
            "ownerId": "7531866",
            "lotId" : "457861"
            
        }
        ]


+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
#GET /lot/{id}/best/        
Returns the best bid of lot

+ Request (application/json)

        {
            "lotId": "457861"
        }


+ Response 200 (application/json)

        {
            "Id":"2345124",
            "bidDate": "2016-10-10T10:00:00",
            "amount": "240",
            "ownerId": "7531866",
            "lotId" : "457861"
            
        }
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
        

#DELETE /bids/{id}
If user change his mind  and he can cancel his bid 

+ Request (application/json)

        {
            "lotId": "457861"
        }

+ Response 200 (text/plain)

        {
                The bid was successful canceled
            
        }
        
+ Response 404 (text/plain)

        {
                Not Found
            
        }


## Feedbacks [/feedbacks]
###List of all feedbacks [GET]


+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
### Create new feedback [POST]
Creating new feedback.

+ Request (application/json)

        {
            "buyerId": "6548987",
            "sellerId": "1234566",
            "lotId" : "564194",
            "mark" : "neutral",
            "title" : "Fast send, lot is not so good",
            "feedback" : "Fast send, lot is not so good"
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /feedbacks/457812

    + Body

            {
                "Id": "457812",
                "buyerId": "6548987",
                "sellerId": "1234566",
                "lotId" : "564194",
                "mark" : "neutral",
                "title" : "Fast send, lot is not so good",
                "feedback" : "Fast send, lot is not so good"
            }


#DELETE /feedbacks/{id}
Deleting feedback by id.

+ Response 204 (application/json)
   
        
+ Response 401 (text/plain)

        Please authorize to see this!
        
+ Response 404 (text/plain)

        No such feedback.

#GET /users/{id}/feedbacks
Show feedbacks performed by/for some user.
       
+ Parameters

    + Id: `1` (number, required) - Id of a user.
    
+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)

        No feedbacks yet.

#GET /lots/{id}/feedbacks
Show feedbacks writed for some lot.
       
+ Parameters

    + id: `1` (number, required) - Id of a lot.
    
+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)

        No feedbacks yet.


## Payments [/payments]
###List of payments [GET]
Show list of payments

+ Response 200 (application/json)

        [
           {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "95431764"
                "lotId": "457861"
                "paymentTypeId": "1"
            }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
    
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
    
+ Response 404 (text/plain)
    
        No payments yet.

## Create a Payment [POST]

+ Request (application/json)

        {
                "paymentAmount": "322",
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
        }

+ Response 201 (application/json)

        {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
        }

#GET /users/{id}/payments

        Show list of user's payments.
+ Parameters
    + id: `1` (number, required) - Id of a user.
+ Response 200 (application/json)

        [
            {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
            },
            
            {
                "Id": "12481633",
                "paymentAmount": "333",
                "payDate": "2016-07-18T2:00:00.620Z"
                "personId": "1234567"
                "lotId": "457862"
                "paymentTypeId": "1"
            }
        ]
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No payments yet.

# GET /payments/{id}

        Get payment by id.
+ Parameters
    + id: `1` (number, required) - Id of a payment.
+ Response 200 (application/json)
        
        [
            {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
            }
        ]
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)
    
        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No payments yet.