FORMAT: 1A
HOST: http://speedsell.apiblueprint.org/

# SpeedSell

SpeedSell is a resource that shows main features of it's parts (Lots, 
Bids, Feedbacks and Payments.

## Lots [/lots]
###List of lots [GET]

## Bids [/bids]
###Show all user bids [GET]
You can get list of all bids made by some user.
###Show all lot bids[GET]
Show the all history of lots, who and when bids was made.
###Show best bids[GET]
Returns the best bets of lots
###Make bid[PUT]
User can choose the lot and make his pown bid
###Cancel bid[DELETE]
If user change his mind  and he can cancel his bid 


## Feedbacks [/feedbacks]
###List of all feedbacks [GET]


+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
###List of feedbacks by sellerId [GET]

+ Request (application/json)

        {
            "sellerId": "7564218"
        }


+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
###List of feedbacks by buyerId [GET]

+ Request (application/json)

        {
            "buyerId": "95431764"
        }


+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
###List of feedbacks by lotId [GET]

+ Request (application/json)

        {
            "lotId": "457861"
        }


+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
###Create feedback [PUT]

###Delete feedback [DELETE]
Deleting 

## Payments [/payments]
###List of payments [GET]
Show list of payments

+ Response 200 (application/json)

        [
           {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "95431764"
                "lotId": "457861"
                "paymentTypeId": "1"
            }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
    
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
    
+ Response 404 (text/plain)
    
        No payments yet.

###User's payments [GET]
Show list of user's payments.

+ Request (application/json)

        {
            "personId": "1234567"
        }
+ Response 200 (application/json)

        [
            {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
            },
            
            {
                "Id": "12481633",
                "paymentAmount": "333",
                "payDate": "2016-07-18T2:00:00.620Z"
                "personId": "1234567"
                "lotId": "457862"
                "paymentTypeId": "1"
            }
        ]
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No payments yet.

###Show payment [GET]
Show the payment information.

+ Request (application/json)
        
        {
            "Id": "12481632"
        }
+ Response 200 (application/json)
        
        [
            {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
            }
        ]
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)
    
        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No payments yet.