FORMAT: 1A
HOST: http://speedsell.apiblueprint.org/

# SpeedSell

SpeedSell is a resource that shows main features of it's parts (Lots, 
Bids, Feedbacks and Payments.

## Lots [/lots]
Show all available lots
#GET /lots/{id}
Show one particular lot 
#GET /users/{id}/lots
Show all lots created by some user
#GET /categories/{id}/lots
Show all lots in some category
##Update lot description  [PATCH /lots/{id}]
Change information in the lot description
## Delete a Lot [DELETE /lots/{id}]

+ Parameters
    + id (string) ... Id of the lot

+ Response 204

## Bids [/bids]
###Show all user bids [GET]
You can get list of all bids made by some user.


+ Response 200 (application/json)

       [
        {
            "Id":"2345123",
            "bidDate": "2016-10-10T09:00:00",
            "amount": "234",
            "ownerId": "7531864",
            "lotId" : "457861"
            
        },
        {
            "Id":"2345188",
            "bidDate": "2016-11-10T09:00:00",
            "amount": "2234",
            "ownerId": "7531864",
            "lotId" : "4578"
            
        }
        ]
    
+ Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }
        
+ Response 401 (application/json)

        {
            "error" : "You are unauthorized to make this request." 
        }
###Show all lot bids[GET]
Show the all history of lots, who and when bids was made.
###Show best bids[GET]
Returns the best bets of lots
###Make bid[PUT]
User can choose the lot and make his pown bid
###Cancel bid[DELETE]
If user change his mind  and he can cancel his bid 


## Feedbacks [/feedbacks]
###List of all feedbacks [GET]


+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        

#GET /users/{id}/feedbacks
Show feedbacks performed by/for some user.
       
+ Parameters

    + Id: `1` (number, required) - Id of a user.
    
+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)

        No feedbacks yet.

#GET /lots/{id}/feedbacks
Show feedbacks writed for some lot.
       
+ Parameters

    + id: `1` (number, required) - Id of a lot.
    
+ Response 200 (application/json)

        [
            {
                "Id": "7531864",
                "buyerId": "95431764",
                "sellerId": "7564218",
                "lotId" : "457861",
                "mark" : "good",
                "title" : "Everything was ok",
                "feedback" : "Fast responce, good lot"
            }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)

        No feedbacks yet.

###Create feedback [PUT]

###Delete feedback [DELETE]
Deleting 


## Payments [/payments]
###List of payments [GET]
Show list of payments

+ Response 200 (application/json)

        [
           {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "95431764"
                "lotId": "457861"
                "paymentTypeId": "1"
            }
        ]
        
+ Response 401 (text/plain)

        Please authorize to see this!
    
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
    
+ Response 404 (text/plain)
    
        No payments yet.

## Create a Payment [POST]

+ Request (application/json)

        {
                "Id": "12481632",
                "paymentAmount": "322",
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
        }

+ Response 201

        {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
        }

#GET /users/{id}/payments

        Show list of user's payments.
+ Parameters
    + id: `1` (number, required) - Id of a post.
+ Response 200 (application/json)

        [
            {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
            },
            
            {
                "Id": "12481633",
                "paymentAmount": "333",
                "payDate": "2016-07-18T2:00:00.620Z"
                "personId": "1234567"
                "lotId": "457862"
                "paymentTypeId": "1"
            }
        ]
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)

        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No payments yet.

# GET /payments/{id}

        Get payment by id.
+ Parameters
    + id: `1` (number, required) - Id of a post.
+ Response 200 (application/json)
        
        [
            {
                "Id": "12481632",
                "paymentAmount": "322",
                "payDate": "2016-07-18T1:58:00.620Z"
                "personId": "1234567"
                "lotId": "457861"
                "paymentTypeId": "1"
            }
        ]
+ Response 401 (text/plain)

        Please authorize to see this!
+ Response 403 (text/plain)
    
        You are not Admin. No way to get this.
+ Response 404 (text/plain)
        
        No payments yet.